# Generated by Django 4.2.8 on 2024-12-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key1", models.CharField(max_length=100)),
                ("key2", models.CharField(max_length=100)),
                ("key3", models.CharField(max_length=100)),
            ],
        ),
    ]
