# Generated by Django 4.2.8 on 2024-12-04 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kafka", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Data",
        ),
    ]
